[tool.black]
line-length = 79
skip-string-normalization = false
skip-magic-trailing-comma = false
include = '\.pyi?$'
exclude = '''
/(
    \.__pycache__
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | db
  | env.py
)/
'''

[tool.isort]
profile = "black"
line_length = 79
skip_gitignore = true
include_trailing_comma = true
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
src_paths = ["src/main"]
exclude = [
    ".venv",
    "__pycache__",
    "migrations",
    "build",
    "dist",
    "db",
    "env.py"
]
